global_defs {
    enable_script_security
    script_user root
}

vrrp_script check_adguard {
    script "/usr/bin/killall -0 adguardhome"
    interval 2
    weight 2
}

vrrp_instance VI_1 {
    state MASTER # MASTER | BACKUP
    interface enp3s0 # eth0 | enp3s0 | wlan0
    virtual_router_id 51
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass password # Change max 8 characters
    }

    virtual_ipaddress {
        {{VIRTUAL_IP_VAR}}/24
    }

    track_script {
        check_adguard
    }
}