app:
  dashboard_url: "https://example.com" # REPLACE THIS WITH YOUR DASHBOARD URL
  log_level: "info"
  save_logs: true
  log_failed_attempts: true

domains:
  domain1:
    base_domain: "example.com" # REPLACE THIS WITH YOUR DOMAIN
    cert_resolver: "letsencrypt"
    prefer_wildcard_cert: true

server:
  external_port: 3000
  internal_port: 3001
  next_port: 3002
  internal_hostname: "pangolin"
  session_cookie_name: "p_session_token"
  resource_access_token_param: "p_token"
  resource_session_request_param: "p_session_request"

traefik:
  cert_resolver: "letsencrypt"
  http_entrypoint: "web"
  https_entrypoint: "websecure"

gerbil:
  start_port: 51820
  base_endpoint: "example.com"
  use_subdomain: false
  block_size: 24
  site_block_size: 30
  subnet_group: 100.89.137.0/20

rate_limits:
  global:
    window_minutes: 1
    max_requests: 100

# optional
# email:
#     smtp_host: "host.hoster.net"
#     smtp_port: 587
#     smtp_user: "no-reply@example.com"
#     smtp_pass: "aaaaaaaaaaaaaaaaaa"
#     no_reply: "no-reply@example.com"

users:
  server_admin:
    email: "admin@example.com"
    password: "Password123$"

flags:
  # require_email_verification: true # email smtp must be enabled to use
  disable_signup_without_invite: true
  disable_user_create_org: true
  allow_raw_resources: true
  allow_base_domain_resources: true
