networks:
  gitea:
    external: false
services:
  server:
    image: docker.io/gitea/gitea:1.23.1
    container_name: gitea
    networks:
      - gitea
    ports:
      - 3001:3000
      - 222:22
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    depends_on:
      - db
  db:
    image: docker.io/library/mysql:8
    container_name: gitea_db
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    restart: always
