services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    ports:
      - 8123:8123 # optional
    volumes:
      - /opt/docker-apps/homeassistant/config:/config
    devices:
      - /path/to/device:/path/to/device # optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped
