- name: Home
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: sunday
        - type: clock
          hour-format: 12h
          timezones:
            - timezone: America/New_York
              label: New York
            - timezone: Europe/Madrid
              label: Madrid
            - timezone: Asia/Tokyo
              label: Tokyo
        - type: bookmarks
          groups:
            - links:
                - title: EchoLink
                  url: https://echo.lan.huffmanks.com
                - title: Github
                  url: https://github.com/huffmanks?tab=repositories
                - title: Tools
                  url: https://tools.huffmanks.com
        # not working with domain, localhost or IP address
        # - type: dynawidgets
        #   widget: linkding-dashboard
        #   title: Linkding
        #   cache: 30m
        #   limit: 10
        #   options:
        #     collapse-after: 5
        #     in-new-tab: true
        #     layout: vertical
        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
              limit: 3
            - url: https://word.huffmanks.com/rss.xml
              title: Weekly Word
              limit: 3

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCyU5wkjgQYGRB0hIHMwm2Sg # Syntax
            - UCkVfrGwV-iG9bSsgCbrNPxQ # Better Stack
            - UCbRP3c757lWg9M-U7TyEkXA # Theo
            - UCUyeluBRhGPCW4rPe_UvBZQ # Primeagen
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee

        - type: group
          widgets:
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: reddit
              subreddit: webdev
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Greenville, South Carolina, United States
          units: imperial
          hour-format: 12h

        - type: server-stats
          servers:
            - type: local
              name: Services

        - type: monitor
          cache: 1m
          title: Monitor
          show-history: true
          sites:
            - title: AdGuard Home
              url: http://{{SERVER_IP_VAR}}:8080
              icon: sh:adguard-home
            - title: Immich
              url: http://{{SERVER_IP_VAR}}:2283
              icon: sh:immich
            # not working
            # - title: Jellyfin
            #   url: http://{{SERVER_IP_VAR}}:8096
            #   icon: sh:jellyfin
            #   method: HEAD

        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: QQQ
              name: Nasdaq 100
            - symbol: DIA
              name: Dow Jones
            - symbol: GLD
              name: Gold
            - symbol: USO
              name: Crude Oil
