services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # No relative paths
      # Left stacks path must === right stacks path
      - /home/{{USERNAME_VAR}}/.opt/stacks:/home/{{USERNAME_VAR}}/.opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/home/{{USERNAME_VAR}}/.opt/stacks
