services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /{{{DOCKER_PATH_VAR}}}/dockge/stacks:{{{DOCKER_PATH_VAR}}}/dockge/stacks
    environment:
      - DOCKGE_STACKS_DIR=/{{{DOCKER_PATH_VAR}}}/dockge/stacks
    restart: unless-stopped
