services:
  dynacat:
    container_name: dynacat
    image: panonim/dynacat
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optional server stats widget
      - /etc/os-release:/host/etc/os-release:ro
      # Optional docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8282:8080
    env_file: .env
