services:
  enclosed:
    container_name: enclosed
    image: corentinth/enclosed
    ports:
      - 8787:8787
    environment:
      SERVER_USE_HTTPS: ${SERVER_USE_HTTPS}
      SERVER_HTTPS_KEY: ${SERVER_HTTPS_KEY}
      SERVER_HTTPS_CERT: ${SERVER_HTTPS_CERT}
      PUBLIC_IS_AUTHENTICATION_REQUIRED: ${PUBLIC_IS_AUTHENTICATION_REQUIRED}
      AUTHENTICATION_JWT_SECRET: ${AUTHENTICATION_JWT_SECRET}
      AUTHENTICATION_USERS: ${AUTHENTICATION_USERS}
    volumes:
      - ./data:/app/.data
    restart: unless-stopped
