services:
  server:
    image: docker.io/gitea/gitea:1.23.1
    container_name: gitea
    networks:
      - gitea
    ports:
      - 3001:3000
      - 222:22
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    image: docker.io/library/mysql:8
    container_name: gitea_db
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    restart: always
networks:
  gitea:
    external: false
