networks:
  gitea-network:
    external: true

services:
  server:
    image: docker.gitea.com/gitea:1.23.5
    container_name: gitea
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      GITEA__database__DB_TYPE: ${GITEA__database__DB_TYPE}
      GITEA__database__HOST: ${GITEA__database__HOST}
      GITEA__database__NAME: ${GITEA__database__NAME}
      GITEA__database__USER: ${GITEA__database__USER}
      GITEA__database__PASSWD: ${GITEA__database__PASSWD}
      LOCAL_ROOT_URL: ${LOCAL_ROOT_URL}
    networks:
      - gitea-network
    ports:
      - "3004:3000"
      - "222:22"
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - db

  db:
    image: docker.io/library/mysql:8
    container_name: gitea_db
    networks:
      - gitea-network
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
