services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - DOWNLOAD_MODE=sequential
      - DELETE_FILE_ON_TRASHCAN=true
      - DEFAULT_OPTION_PLAYLIST_STRICT_MODE=true
      - OUTPUT_TEMPLATE=%(uploader,playlist_title)s/%(title)s_%(id)s/%(title)s_%(id)s.%>
      - RATELIMIT=5M
      - YTDL_OPTIONS_FILE=/config/options.json
      - TEMP_DIR=/tmp-downloads
    volumes:
      - ./data/downloads:/downloads
      - ./config/options.json:/config/options.json:ro
      - ./tmp:/tmp-downloads

  nfo-gen:
    image: python:3.11-slim
    container_name: nfo-generator
    user: "1000:1000"
    volumes:
      - ./data/downloads:/downloads
      - ./config/nfo-script.sh:/nfo-script.sh
    environment:
      - HOME=/tmp
    entrypoint: ["/bin/bash", "/nfo-script.sh"]
    restart: unless-stopped
