networks:
  gitea-network:
    external: true

services:
  mirror-to-gitea:
    container_name: mirror-to-gitea
    image: jaedle/mirror-to-gitea:latest
    restart: unless-stopped
    networks:
      - gitea-network
    environment:
      GITEA_URL: ${GITEA_URL}
      GITEA_TOKEN: ${GITEA_TOKEN}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MIRROR_PRIVATE_REPOSITORIES: ${MIRROR_PRIVATE_REPOSITORIES}
