services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    ports:
      - 8443:443
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    networks:
      - nextcloud_network
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
    volumes:
      - ./config:/config
      - /{{{DOCKER_PATH_VAR}}}/nextcloud/data:/data
    restart: unless-stopped
  nextcloud_db:
    image: postgres:alpine
    container_name: nextcloud_db
    networks:
      - nextcloud_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - nextcloud_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    networks:
      - nextcloud_network
    volumes:
      - nextcloud_redis:/data
    restart: unless-stopped
networks:
  nextcloud_network:
    name: nextcloud_network
    driver: bridge
volumes:
  nextcloud_pgdata:
    name: nextcloud_pgdata
  nextcloud_redis:
    name: nextcloud_redis
