services:
  norish:
    image: norishapp/norish:latest
    container_name: norish-app
    restart: always
    ports:
      - "3009:3000"
    user: "1000:1000"
    volumes:
      - norish_data:/app/uploads
    environment:
      AUTH_URL: ${AUTH_URL}
      DATABASE_URL: ${DATABASE_URL}
      MASTER_KEY: ${MASTER_KEY}
      OBSCURA_ENDPOINT: ${OBSCURA_ENDPOINT}
      REDIS_URL: ${REDIS_URL}
      UPLOADS_DIR: ${UPLOADS_DIR}
      TRUSTED_ORIGINS: ${TRUSTED_ORIGINS}
      BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS}
      PASSWORD_AUTH_ENABLED: ${PASSWORD_AUTH_ENABLED}
      ENABLE_REGISTRATION: ${ENABLE_REGISTRATION}
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    container_name: norish-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  obscura:
    image: norishapp/obscura:0.2.0-norish.1
    container_name: norish-obscura
    restart: unless-stopped

  redis:
    image: redis:8.4.0
    container_name: norish-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  norish_data:
  redis_data:
