services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 3007:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data:/app/backend/data
    restart: always
volumes:
  open-webui:
    external: true
    name: open-webui
