services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-ngx-redis
    volumes:
      - /{{{DOCKER_PATH_VAR}}}/paperless-ngx/redis/data:/data
    restart: unless-stopped

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    depends_on:
      - broker
    ports:
      - "8001:8000"
    volumes:
      - /{{{DOCKER_PATH_VAR}}}/paperless-ngx/data:/usr/src/paperless/data
      - /{{{DOCKER_PATH_VAR}}}/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:
