services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    ports:
      - 8945:8945
    volumes:
      - /{{{DOCKER_PATH_VAR}}}/pinchflat/config:/config
      - /{{{DOCKER_PATH_VAR}}}/pinchflat/downloads:/downloads
    environment:
      - TZ=America/New_York
    restart: unless-stopped
