services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    ports:
      - 8945:8945
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - TZ=America/New_York
    restart: unless-stopped
