services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    user: "1000:1000"
    ports:
      - 8945:8945
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - TZ=America/New_York
    depends_on:
      - pot-provider
    restart: unless-stopped
  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: pot-provider
    init: true
    ports:
      - 4416:4416
    restart: always
