services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    volumes:
      - /{{{DOCKER_PATH_VAR}}}/plex/config:/config
      - /path/to/tvseries:/tv
      - /path/to/movies-01:/movies/movies-01
      - /path/to/movies-02:/movies/movies-02
      - /path/to/youtube:/youtube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    restart: unless-stopped
