source:
  github:
    - token: "YOUR_GITHUB_TOKEN"
      wiki: false
      issues: false
      starred: false
      gists: true

destination:
  gitea:
    - token: "YOUR_GITEA_TOKEN"
      user: "YOUR_GITEA_USERNAME"
      url: http://localhost:3004
      lfs: false
      mirror:
        enabled: true
        mirrorinterval: 2h0m0s
