source:
  github:
    - token: "YOUR_GITHUB_TOKEN"
      wiki: false
      issues: false
      starred: false
      gists: true

destination:
  local:
    - path: "/home/{USERNAME_VAR}/Documents/gh-backup"
      structured: true
      bare: true
      mirror: true
