source:
  github:
    - token: "YOUR_GITHUB_TOKEN"
      wiki: false
      issues: false
      starred: false
      gists: true

destination:
  local:
    - path: "PATH_TO_LOCAL_BACKUP"
      structured: true
      bare: true
      mirror: true
